DROP TABLE IF EXISTS product;
 /*
CREATE TABLE product (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  quantity INT NOT NULL, 
  price DOUBLE NOT NULL
);
*/
/*
CREATE TABLE IF NOT EXISTS product (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  quantity INT NOT NULL, 
  price DOUBLE NOT NULL
);
*/

